routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//route admin regroupees
Route::group(['middleware' => 'auth'], function(){
        // Route users admin
    Route::resource('admin/users', 'AdminUsersController');


    // Route posts admin
    Route::resource('admin/posts', 'AdminPostsController');

        // Route medias
    Route::get('admin/medias', 'AdminMediasController@index')->name('medias.index');

    Route::get('admin/medias/{medias}/edit', 'AdminMediasController@edit')->name('medias.edit');

    Route::get('admin/medias/upload', 'AdminMediasController@upload')->name('medias.upload');

    Route::delete('admin/medias/{medias}', 'AdminMediasController@destroy')->name('medias.destroy');

    Route::post('admin/medias', 'AdminMediasController@store')->name('medias.store');

        // Route catgories
    Route::resource('admin/categories', 'AdminCategoriesController');

    // Route comments
    Route::resource('/admin/comments', 'AdminCommentsController', ['only' => ['index', 'edit', 'update', 'destroy']]);

    // Route admin 
    Route::get("/admin", "AdminController@dashboard")->name('dashboard');

    Route::match(['put', 'patch'], 'admin/medias/{medias}', 'AdminMediasController@update')->name('medias.update');

});


Route::post('posts/comments/{id}', 'PostsController@comments')->name('posts.comments');
// Route posts visiteurs
Route::resource('posts', 'PostsController', ['only' => ['index', 'show'],
                                            'as' => 'visiteurs'
                                            ]
);

// Route categories visiteurs
Route::resource('categories', 'CategoriesController', ['only' =>['index', 'show'],
                                            'as' => 'visiteurs'
                                            ]

);






//// Route home
//Route::get("/", "HomeController@affich");




Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

// Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    protected $fillable = [

        "post_id",
        "is_active",
        "content",
        "author",
        "email"


    ];

    public function post(){

        return $this->belongsTo("App\Post");

    }

}

resources/views/admin/comments/delete.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Delete</title>
</head>
<body>
    Delete !
</body>
</html>

resources/views/admin/comments/edit.blade.php
@extends('layouts.app')

@section('content')

<header><a href="{{route('comments.index')}}">Accueil</a></header>

{!! Form::model($Comment, ['method' => 'PATCH', 'action' => ['AdminCommentsController@update', $Comment->id]]) !!}

    {!! Form::label('content', 'Contenu') !!}
    {!! Form::textarea('content', null) !!}

    {!! Form::label('author', 'Auteur') !!}
    {!! Form::text('author', null) !!}

    {!! Form::label('email', 'Email') !!}
    {!! Form::text('email', null) !!}

    {!! Form::label('is_active', 'Affichage') !!}
    {!! Form::select('is_active', ['0' => 'Inactif', '1' => 'Actif'], null) !!}

    {!! Form::submit('Mettre à jour') !!}

{!! Form::close() !!}

{!! Form::open(['method' => 'DELETE', 'action' => ['AdminCommentsController@destroy', $Comment->id]]) !!}

{!! Form::submit('Supprimer') !!}

{!! Form::close() !!}

<p>Article associé</p>

{{$Comment->post->content}}

@stop

resources/views/admin/comments/index.blade.php
@extends('layouts.app')

@section('content')

<header><a class="waves-effect waves-light btn" href="{{route('dashboard')}}">TABLEAU DE BORD</a></header>

<ul>
    @foreach($comments as $comment)
        <li><a href="{{route('posts.show', $comment->post->id)}}">{{$comment->post->title}}</a>
        {{$comment->content}}
        {{$comment->author}}
        {{$comment->email}}
        @if ($comment->is_active == 0)
            <p>Inactif</p>
            @else
            <p>Actif</p>
        @endif
        
        <a href="{{route('comments.edit', $comment->id)}}">Modifier</a></li>
        {!! Form::open(['method' => 'DELETE', 'action' => ['AdminCommentsController@destroy', $comment->id]]) !!}

            {!! Form::submit('Supprimer') !!}

        {!! Form::close() !!}

    @endforeach
</ul>


@stop