routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//route admin regroupees
Route::group(['middleware' => 'auth'], function(){
        // Route users admin
    Route::resource('admin/users', 'AdminUsersController');


    // Route posts admin
    Route::resource('admin/posts', 'AdminPostsController');

        // Route medias
    Route::get('admin/medias', 'AdminMediasController@index')->name('medias.index');

    Route::get('admin/medias/{medias}/edit', 'AdminMediasController@edit')->name('medias.edit');

    Route::get('admin/medias/upload', 'AdminMediasController@upload')->name('medias.upload');

    Route::delete('admin/medias/{medias}', 'AdminMediasController@destroy')->name('medias.destroy');

    Route::post('admin/medias', 'AdminMediasController@store')->name('medias.store');

        // Route catgories
    Route::resource('admin/categories', 'AdminCategoriesController');

    // Route comments
    Route::resource('/admin/comments', 'AdminCommentsController', ['only' => ['index', 'edit', 'update', 'destroy']]);

    // Route admin 
    Route::get("/admin", "AdminController@dashboard")->name('dashboard');

    Route::match(['put', 'patch'], 'admin/medias/{medias}', 'AdminMediasController@update')->name('medias.update');

});


Route::post('posts/comments/{id}', 'PostsController@comments')->name('posts.comments');
// Route posts visiteurs
Route::resource('posts', 'PostsController', ['only' => ['index', 'show'],
                                            'as' => 'visiteurs'
                                            ]
);

// Route categories visiteurs
Route::resource('categories', 'CategoriesController', ['only' =>['index', 'show'],
                                            'as' => 'visiteurs'
                                            ]

);






//// Route home
//Route::get("/", "HomeController@affich");




Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

// Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function roles() {
        return $this->belongsToMany('App\Role');

    }

    public function photos() {
        return $this->morphMany('App\Photo', 'imageable');
    }

    public function posts() {
        return $this->hasMany('App\Post');
    }

    public function isAdmin(){

        return ($this->roles->name == 'Administrateur') ? true : false;

    }

}

resources/views/admin/users/create.blade.php
@extends('layouts.app')

@section('content')

<header><a href="{{route('users.index')}}">Accueil</a></header>

{!! Form::open(['method' => 'POST', 'action' => 'AdminUsersController@store', 'files' => true]) !!}

    {!! Form::label('name', 'Nom') !!}
    {!! Form::text('name', null) !!}

    {!! Form::label('password', 'Mot de passe') !!}
    {!! Form::text('password', null) !!}

    {!! Form::label('email', 'Email') !!}
    {!! Form::text('email', null) !!}

    {!! Form::label('is_active', 'Affichage') !!}
    {!! Form::select('is_active', ['0' => 'Inactif', '1' => 'Actif']) !!}

    {!! Form::file('file') !!}

    {!! Form::submit("Créer l'utilisateur") !!}

{!! Form::close() !!}




@stop

resources/views/admin/users/delete.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Delete</title>
</head>
<body>

</body>
</html>

resources/views/admin/users/edit.blade.php
@extends('layouts.app')

@section('content')

{!! Form::model($User, ['method' => 'PATCH', 'action' => ['AdminUsersController@update', $User->id], 'files' => true]) !!}

    {!! Form::label('name', 'Nom') !!}
    {!! Form::text('name', null) !!}

    {!! Form::label('password', 'Mot de passe') !!}
    {!! Form::text('password', null) !!}

    {!! Form::label('email', 'Email') !!}
    {!! Form::text('email', null) !!}

    {!! Form::label('is_active', 'Affichage') !!}
    {!! Form::select('is_active', ['0' => 'Inactif', '1' => 'Actif'], null) !!}

    {!! Form::file('file', null) !!}

    {!! Form::submit("Mettre à jour") !!}

{!! Form::close() !!}




@stop

resources/views/admin/users/index.blade.php
@extends("layouts.app")


@section('content')

<header><a class="waves-effect waves-light btn greyss" href="{{route('dashboard')}}">TABLEAU DE BORD</a></header>

<ul class="collection">
    @foreach($users as $user)
    <li class="collection-item avatar"><a href="{{route('users.show', $user->id)}}">{{$user->name}}</a>
    <img src="{{$user->photos()->first() ? '/images/' . $user->photos()->first()->file : 'http://via.placeholder.com/50x50'}}" alt="" class="circle">
    <a href="#!" class="secondary-content"><i class="material-icons ">grade</i></a>
    </li>
    @endforeach
</ul>

    <p><a class="waves-effect waves-light btn greyss" href="{{route('users.create')}}">Créer un utilisateur</a></p>

    @stop

resources/views/admin/users/show.blade.php
@extends('layouts.app')

@section('content')

<header><a href="{{route('users.index')}}">Accueil</a></header>

{{$User->name}}

<p>Ses articles</p>
<ul>
    @foreach($User->posts as $post)
        <li><a href="{{route('posts.show', $post->id)}}">{{$post->title}}</a></li>
    @endforeach
</ul>

@foreach ($User->photos as $photo)

<img src='/images/{{$photo->file}}' />
@endforeach


<p><a href="{{route('users.edit', $User->id)}}">Modifier</a></p>

{!! Form::open(['method' => 'DELETE', 'action' => ['AdminUsersController@destroy', $User->id]]) !!}

    {!! Form::submit('Supprimer') !!}

{!! Form::close() !!}

@stop