routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//route admin regroupees
Route::group(['middleware' => 'auth'], function(){
        // Route users admin
    Route::resource('admin/users', 'AdminUsersController');


    // Route posts admin
    Route::resource('admin/posts', 'AdminPostsController');

        // Route medias
    Route::get('admin/medias', 'AdminMediasController@index')->name('medias.index');

    Route::get('admin/medias/{medias}/edit', 'AdminMediasController@edit')->name('medias.edit');

    Route::get('admin/medias/upload', 'AdminMediasController@upload')->name('medias.upload');

    Route::delete('admin/medias/{medias}', 'AdminMediasController@destroy')->name('medias.destroy');

    Route::post('admin/medias', 'AdminMediasController@store')->name('medias.store');

        // Route catgories
    Route::resource('admin/categories', 'AdminCategoriesController');

    // Route comments
    Route::resource('/admin/comments', 'AdminCommentsController', ['only' => ['index', 'edit', 'update', 'destroy']]);

    // Route admin 
    Route::get("/admin", "AdminController@dashboard")->name('dashboard');

    Route::match(['put', 'patch'], 'admin/medias/{medias}', 'AdminMediasController@update')->name('medias.update');

});


Route::post('posts/comments/{id}', 'PostsController@comments')->name('posts.comments');
// Route posts visiteurs
Route::resource('posts', 'PostsController', ['only' => ['index', 'show'],
                                            'as' => 'visiteurs'
                                            ]
);

// Route categories visiteurs
Route::resource('categories', 'CategoriesController', ['only' =>['index', 'show'],
                                            'as' => 'visiteurs'
                                            ]

);






//// Route home
//Route::get("/", "HomeController@affich");




Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

// Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = [
        "name"
    ];

    public function posts(){

        return $this->hasMany("App\Post");
    }

    public function photos(){
        return $this->morphMany("App\Photo", 'imageable');
    }

}

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $Categories = Category::all();
        return view ('categories.index', compact('Categories'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $Category = Category::findOrFail($id);
        return view ('categories.show', compact('Category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */




}

resources/views/admin/categories/create.blade.php
@extends('layouts.app')

@section('content')

    <header><a class="waves-effect waves-light btn" href="{{route('categories.index')}}">Accueil</a></header>

    {!! Form::open(['method' => 'POST', 'action' => ['AdminCategoriesController@store'], 'files' => true]) !!}

    {!! Form::label('name', 'Nom') !!}

    {!! Form::text('name', null)!!} <br />

    {!! Form::file('file', null) !!}

    {!! Form::submit('Créer la catégorie') !!}






    {!! Form::close() !!}


    @stop

resources/views/admin/categories/edit.blade.php
@extends('layouts.app')

@section('content')

    <header><a href="{{route('categories.index')}}">Accueil</a></header>

    {!! Form::model($Category, ['method'=> "PATCH", 'action'=> ["AdminCategoriesController@update", $Category->id], 'files' => true]) !!}

    {!! Form::label('name', 'Nom') !!}
    {!! Form::text('name', null) !!}

    {!! Form::submit('Mettre à jour') !!}

    {!! Form::file('file', null) !!}

    {!! Form::close() !!}




    {!! Form::open(['method'=> "DELETE", 'action'=> ["AdminCategoriesController@destroy", $Category->id]]) !!}

    {!! Form::submit('Supprimer') !!}

    {!! Form::close() !!}






@stop

resources/views/admin/categories/index.blade.php
@extends('layouts.app')

@section('content')

    <header><a class="waves-effect waves-light btn" href="{{route('dashboard')}}">TABLEAU DE BORD</a></header>

    <ul>
     @foreach($categories as $category)

            <li> <a  href="{{route('categories.show', $category->id)}}">{{$category->name}} </a> </li>




     @endforeach
    </ul>

    <p><a class="waves-effect waves-light btn" href="{{route('categories.create')}}">Créer une catégorie</a></p>


@stop

resources/views/admin/categories/show.blade.php
@extends("layouts.app")

@section("content")

    <header><a href="{{route('categories.index')}}">Accueil</a></header>
    @foreach($Category->photos as $photo)

    <img src="/images/{{$photo->file}}"/> 
    @endforeach
 



    <p>{{$Category->name}}</p>

    <p>Articles : </p>
    <ul>
    @foreach($Category->posts as $post)
            <li><a href="{{route('posts.show', $post->id)}}">{{$post->title}}</a></li>
    @endforeach
    </ul>

    <p><a href="{{route("categories.edit", $Category->id)}}">Modifier</a></p>

    {!! Form::open(["method" => "DELETE", "action" => ["AdminCategoriesController@destroy", $Category->id]]) !!}

        {!! Form::submit("Supprimer") !!}

    {!! Form::close()!!}

@stop